spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: archmindDB
server:
  port: 8080
  # application.yaml
  spring:
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration